### ISSUE TITLE
Error while converting ItemStack to JSON on PaperMC

### ISSUE THREAD

**Issue by KillerOfPie** [Tradeshop/tradeshop-LOG#1]
This error only appears if the server is running a PaperMC jar.

`[12:22:04] [Server thread/ERROR]: Could not pass event PlayerSuccessfulTradeEvent to TradeShop-LOG v0.0.2-DEV
java.lang.AssertionError: java.lang.NoSuchFieldException: ARMOR
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:808) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.toJson(Gson.java:661) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.toJsonTree(Gson.java:562) ~[patched_1.17.1.jar:git-Paper-226]
	at com.google.gson.Gson.toJsonTree(Gson.java:541) ~[patched_1.17.1.jar:git-Paper-226]
	at org.shanerx.tradeshoplog.utils.logging.TransactionLogger.getItemListAsString(TransactionLogger.java:89) ~[tradeshop-log-0.0.2-DEV-2021-08-28T00.45.38.jar:?]
	at org.shanerx.tradeshoplog.utils.logging.TransactionLogger.logTransaction(TransactionLogger.java:79) ~[tradeshop-log-0.0.2-DEV-2021-08-28T00.45.38.jar:?]
	at org.shanerx.tradeshoplog.listeners.SuccessfulTradeEventListener.onSuccessfulTrade(SuccessfulTradeEventListener.java:46) ~[tradeshop-log-0.0.2-DEV-2021-08-28T00.45.38.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-226]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-226]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-226]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-226]
	at org.shanerx.tradeshop.listeners.ShopTradeListener.onBlockInteract(ShopTradeListener.java:177) ~[tradeshop-2.3.0-DEV-2021-08-28T00.47.34.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-226]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-226]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-226]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-226]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:538) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:510) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1735) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1363) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1342) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1335) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1296) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1207) ~[patched_1.17.1.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patched_1.17.1.jar:git-Paper-226]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchFieldException: ARMOR
	at java.lang.Class.getField(Class.java:2086) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:797) ~[patched_1.17.1.jar:git-Paper-226]
	... 56 more`

**Comment by SparklingComet** [comment]
> if the server is running a PaperMC jar

How about regular Spigot? Does it work perfectly?

> `java.lang.NoSuchFieldException: ARMOR`

Could you please try Paper 1.15?

**Comment by SparklingComet** [comment]
From what I gather the issue lies with this line: 

```Java
    private String getItemListAsString(List<ShopItemStack> itemList) {
        final Gson gson = new GsonBuilder().create();
        JsonObject jsonObj = new JsonObject();
        for (int i = 0; i < itemList.size(); i++) {
            jsonObj.add(i + "", gson.toJsonTree(itemList.get(i).getItemStack())); // toJsonTree call
        }

        return gson.toJson(jsonObj);
    }
```

https://github.com/Tradeshop/tradeshop-LOG/blob/main/src/main/java/org/shanerx/tradeshoplog/utils/logging/TransactionLogger.java#L95

Perhaps an internal change by Paper concerning inventories broken itemstack (de-)serialisation? (Since some kind of ARMOR attribute seems to be missing…)

**Comment by KillerOfPie** [comment]
> From what I gather the issue lies with this line:
> 
> ```java
>     private String getItemListAsString(List<ShopItemStack> itemList) {
>         final Gson gson = new GsonBuilder().create();
>         JsonObject jsonObj = new JsonObject();
>         for (int i = 0; i < itemList.size(); i++) {
>             jsonObj.add(i + "", gson.toJsonTree(itemList.get(i).getItemStack())); // toJsonTree call
>         }
> 
>         return gson.toJson(jsonObj);
>     }
> ```
> 
> https://github.com/Tradeshop/tradeshop-LOG/blob/main/src/main/java/org/shanerx/tradeshoplog/utils/logging/TransactionLogger.java#L95

Correct, not sure what actually causes it though.

> > if the server is running a PaperMC jar
> 
> How about regular Spigot? Does it work perfectly?
> 
> > `java.lang.NoSuchFieldException: ARMOR`
> 
> Could you please try Paper 1.15?

Tested on 1.17.1 Spigot, everything works as expected.
Changed Jar and only Jar to Paper 1.17.1-226, and the problem exists.

I will test on 1.15 Paper and make another reply

**Comment by SparklingComet** [comment]
> Correct, not sure what actually causes it though.

please read edit

**Comment by KillerOfPie** [comment]
Tested, 1.15 Paper has a similar problem
```
Could not pass event PlayerSuccessfulTradeEvent to TradeShop-LOG v0.0.2-DEV
java.lang.StackOverflowError: null
```
Spigot does work properly

**Comment by KillerOfPie** [comment]
> > Correct, not sure what actually causes it though.
> 
> please read edit

Ill report the problem on the PaperMC github and see if we get anywhere there.

**Comment by SparklingComet** [comment]
> Ill report the problem on the PaperMC github and see if we get anywhere there.
 
Alright, can you link the report when you do?

**Comment by KillerOfPie** [comment]
https://github.com/PaperMC/Paper/issues/6515

**Comment by KillerOfPie** [comment]
Fixed with https://github.com/Tradeshop/TradeShop/commit/1739fc712a18aa1f8593d2b5f1a0d85c5ac3356c on Tradeshop
